### ISSUE TITLE
[1.342] Smoothing bug on curve extrusions

### ISSUE THREAD

**Issue by AtomicJoe1** [LogicalError/realtime-CSG-for-unity#153]
This how it looks like:
http://i.imgur.com/vMyy0Ai.jpg

and this is the CSG prefab:
https://dl.dropboxusercontent.com/u/73405767/CSG_Test.prefab

I know it can be mitigated using more polygons, but I want to rely on polygon smoothing and tessellation for easy and fast scalability.
What I do now is I export it to FBX and fix it on an external 3D software, but it's not that simple, since the generated mesh has creases because it has some little cracks and holes.

**Comment by LogicalError** [comment]
Ok thanks, I'll take a look

**Comment by LogicalError** [comment]
I fixed the smoothing issues in version 1.339!
You can download this version from the update site here https://prenominal.nl/updates/
Once this version is available from the asset store I'll close this ticket

**Comment by AtomicJoe1** [comment]
I just tested v 1.339.
Still the same issues, even worse: now if you manually apply smoothing, instead of just ignore you, it smoothes it out badly.
Check the images.
![csgbug01](https://cloud.githubusercontent.com/assets/24545078/21297703/bb165aec-c584-11e6-9657-e3e83228a535.jpg)
![csgbug02](https://cloud.githubusercontent.com/assets/24545078/21297704/bf36f640-c584-11e6-9c8b-f5c4ea3124d9.jpg)
![csgbug03](https://cloud.githubusercontent.com/assets/24545078/21297705/c1dd8e0e-c584-11e6-8158-2a9005ac8bf4.jpg)
![csgbug04](https://cloud.githubusercontent.com/assets/24545078/21297706/c3d025b4-c584-11e6-8530-fb4024a31386.jpg)

**Comment by AtomicJoe1** [comment]
here you have the CSG prefab for testing:
https://dl.dropboxusercontent.com/u/73405767/CSG_Test_v1_339.prefab

Anyway, I didn't do anything fancy, just a smoothed free-draw and adjusted the spline handles (curve type ALIGNED)

**Comment by LogicalError** [comment]
Ok thanks for testing. Odd that I didn't see anything in my own tests. I'll take a look at these.
I have an idea what might be the cause (at least for the majority of these artifacts)

**Comment by LogicalError** [comment]
What platform are you on by the way?

**Comment by AtomicJoe1** [comment]
Windows 10 pro 64bits.
I have tested this on a laptop and on a desktop PC with the same results.

**Comment by LogicalError** [comment]
I (partially?) fixed this in 1.340 which you can find on the update site. It seems the majority of the issues had to do that not all sides always where assigned to the same smoothing groups. To fix this on existing surfaces you'll have to select all surfaces and click on smooth in the surface tool. For new shapes this should work correctly in 1.340. I'll test some more to see if there are any more issues

**Comment by LogicalError** [comment]
More improvements to smoothing can be found in 1.341
There's still an issue remaining where multiple brushes intersect on the same edge

**Comment by LogicalError** [comment]
I just released version 1.342, which should fix this issue!
https://prenominal.nl/forum3/showthread.php?tid=32
I'll close this ticket when this version is available from the asset store

**Comment by LogicalError** [comment]
this version is available from the asset store, so I'll close this ticket
