### ISSUE TITLE
[Fix Available 1.305] Object movement / UI issue

### ISSUE THREAD

**Issue by MarisaLovesUsAll** [LogicalError/realtime-CSG-for-unity#20]
With small zoom, objects became unmoveable because the scale UI hitboxes are overlapping the move hitbox.
Cursor is right in the middle of object, but LMB click and drag isn't moving the object, but scales it to the side.
<img width="643" alt="untitled" src="https://cloud.githubusercontent.com/assets/5061652/19369645/53073fba-91af-11e6-88a8-5b63e058716b.png">

2K display, windows 10, any scaling (tested with 100%, 125% and 150%).

**Comment by LogicalError** [comment]
Hmm .. that's tricky to solve considering that if I let you move the object in this particular case, someone else will then subsequently tell me that in that case he/she wants to scale it ..  :-/
If you have any suggestions on how to solve this, let me know
I'll give this some thought

**Comment by MarisaLovesUsAll** [comment]
Maybe apply something like adaptive UI on very low resolutions? If movement hitbox size is scaled to less than 3 px, make it 3 px, and stick the scale hitboxes to the edges of movement hitbox.
I.e. let hitboxes have a minimum width/height.
![untitled](https://cloud.githubusercontent.com/assets/5061652/19380366/a5556206-91ff-11e6-876f-2eca028f24ca.png)

What do you think about it?

**Comment by LogicalError** [comment]
Fixed in version 1.305, which is available on the update site ( http://prenominal.nl/updates/index.php )
I will close this ticket once this is available on the asset store

**Comment by MarisaLovesUsAll** [comment]
A lot better! Still not perfect on very low zoom, but pretty sufficient. Thanks!

**Comment by LogicalError** [comment]
I'll see if I can improve things
