### ISSUE TITLE
[Fix Available 1.311] Smoothing Separated Surfaces

### ISSUE THREAD

**Issue by Hisashimaru** [LogicalError/realtime-CSG-for-unity#40]
Is ReltimeCSG difficult to support smooth separated object surfaces? I want to smoothing like this edges.
![separeted](https://cloud.githubusercontent.com/assets/7605365/19709814/71bb1ddc-9b64-11e6-84ea-e95c46e7a8c6.jpg)

**Comment by LogicalError** [comment]
You can select the surfaces you want to smooth between and press the smooth button in the tool window in surface edit mode

**Comment by Hisashimaru** [comment]
oh, My question is bad. Can I smooth the surfaces of the different objects.
![gif](https://cloud.githubusercontent.com/assets/7605365/19716824/be86e86a-9b98-11e6-81c5-7d7f384d77ff.gif)

**Comment by LogicalError** [comment]
Looks like something got broken, that's supposed to work :(

**Comment by Hisashimaru** [comment]
That's great! I hope you fix that soon.

**Comment by LogicalError** [comment]
I'll look at it tonight. It must be a small thing that broke this since I didn't actually touch this code in a long time.. so it _should_ be easy to fix

**Comment by LogicalError** [comment]
This issue is fixed in version 1.309 which is available on the update site 
( http://prenominal.nl/updates/index.php )
I will close this ticket when it's available on the asset store

**Comment by Hisashimaru** [comment]
Thanks fast supports!
I have tried smoothing, but it still doesn't work. I made two same shapes with the box tool and the free draw tool. The free draw tool is good smoothing, but the box tool is not.

I checked on the scene view which drawing face normals.
![edgesmooth](https://cloud.githubusercontent.com/assets/7605365/19750874/f62ef1d0-9c2f-11e6-9266-4dc697ec595a.jpg)

ReatimeCSG 1.309

**Comment by LogicalError** [comment]
Did you select the surfaces + press smooth in the surface edit mode?
If you did, can you sent me those two shapes to my email address so that I can take a closer look?
You can find my email address on the top right corner at https://logicalerror.github.io/
Thanks

**Comment by LogicalError** [comment]
Ok, I confirmed that there's something wrong with the smoothing. I'll look into it.

**Comment by LogicalError** [comment]
This issue is fixed in version 1.311 which is available on the update site 
( http://prenominal.nl/updates/index.php )
I will close this ticket when it's available on the asset store

**Comment by LogicalError** [comment]
Fix is in the version that's on the asset store now, so closing ticket
