### ISSUE TITLE
[FIX AVAILABLE] Cannot move or rotate camera anymore

### ISSUE THREAD

**Issue by LogicalError** [LogicalError/realtime-CSG-for-unity#6]
Something triggers this bug in Unity, it might be interactions with other plugins.. I'm still investigation.
However, a work-around is that you can reset your camera by going in and out of play mode

**Comment by LogicalError** [comment]
Fix available on asset store

**Comment by jhinton2** [comment]
This bug is still happening after I create a brush in 1.004. Using an empty project with Unity 5.4

**Comment by LogicalError** [comment]
Hi,
Can you try to see if it's fixed in 1.101?
You can find the beta download from here https://logicalerror.github.io/

**Comment by jhinton2** [comment]
Yeah still happening in 1.101 :(

**Comment by LogicalError** [comment]
ok, is realtime CSG the only plugin you're using in that project? and do
you have a way of reproducing the bug? (that would be very helpful)

**Comment by jhinton2** [comment]
Its a empty project. 
Create brush outline. 
Pull brush up using green arrow/handle. 
Rotate camera with Mouse/Alt key (working at this point). 
Release mouse and stop rotating camera. Now I can no longer rotate.

**Comment by LogicalError** [comment]
did you start moving the camera while still pulling up the brush, or did
you release your mouse before?
Also, if you don't use ALT, does it still happen?
You're the first to report this happening this quickly and this easily ..
so I'm trying to figure out what is different
this camera locking thing is technically a Unity bug, but somehow I'm
triggering it :-/

**Comment by jhinton2** [comment]
Pull the brush up then release the mouse. Then use alt/mouse to rotate. and it happens every time. If you click off the brush before rotating it wont get stuck.

Also just noticed if you just create the outline and try to rotate it breaks as well. After this I can't cant finish drawing brushes any more. The eye icon is stuck on.

**Comment by jhinton2** [comment]
Just hold right mouse and rotating doesn't seem to cause any issues.

**Comment by LogicalError** [comment]
So it only happens when you hold both mouse buttons at the same time?

**Comment by jhinton2** [comment]
No. Alt + Left Mouse

**Comment by LogicalError** [comment]
I'll try to fix this, but it's already late here so it will have to wait
until tomorrow.. in the meantime if it happens because you're pressing both
mouse buttons at the same time then a temporary workaround is ... not
pressing both mouse buttons at the same time ;)
Sorry for the inconvenience

**Comment by jhinton2** [comment]
NP. But to be clear. I'm not pressing both mouse buttons. 
Holding Alt + Left Mouse Button and dragging will orbit the camera around the current pivot. Holding Right Mouse Button and dragging just rotates the camera locally. 

https://docs.unity3d.com/Manual/SceneViewNavigation.html

**Comment by LogicalError** [comment]
Right, oddly enough this conversation arrived out of order in my email box.  But anyway, I've uploaded a fix to the beta site (version 1.102)! Let me know if it works for you. (I'll close this bug when it's on the asset store)

**Comment by jhinton2** [comment]
Initially I thought it was fixed but I mess around some more and got it to happen a few times. It's a bit harder to repro now. I think it comes down to blocking the camera orbit in some of the modes (Mesh/Clip). This is also a usability issue. You should be able to orbit no matter what mode is active. If I get some time ill try and get specific repro for you.

**Comment by LogicalError** [comment]
Hmm ok, I hoped that was the last of this kind of bug. Thanks for helping
me track them down..

**Comment by LogicalError** [comment]
@jhinton2 I submitted a new version that should have the problems fixed in Object mode. I'm going through every edit mode, piece by piece, so it'll take a couple of days before I manage to go through them all.

**Comment by jhinton2** [comment]
Ok sounds good. Let me know and ill do some more testing on it.

**Comment by LogicalError** [comment]
New update is available (version 1.202) which should fix camera issues with mesh mode.
Also fixed the brush drawing part wrt to camera issues, although the camera is still locked for now, I'll get to that later.

**Comment by LogicalError** [comment]
@jhinton2 the latest version on the beta site (version 1.203) should fix all the sticky camera issues! Let me know if you run into any issues or have feature requests etc.

**Comment by LogicalError** [comment]
Note: I will close this bug when it's available on the asset store

**Comment by jhinton2** [comment]
I gave the latest a try. The rotating seems a lot better.

**Comment by LogicalError** [comment]
These fixes are now in version 1.204 which is now available on the asset store, let me know if you run into "Camera getting stuck" issues again
